version: '3.8'

services:
  ros-dev:
    image: miracatici/ros-dev:22.04-humble
    container_name: ros-dev
    hostname: ros-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=$DISPLAY
    command: bash
    tty: true
